_wandb:
    value:
        cli_version: 0.27.2
        code_path: code/src/01_mlp_hopper.py
        e:
            nvj1vbb34l1jjkqd4zhfhjxq62nacihe:
                apple:
                    ecpuCores: 6
                    gpuCores: 10
                    macModel: Mac16,1
                    memoryGb: 16
                    name: Apple M4
                    pcpuCores: 4
                    ramTotalBytes: "17179869184"
                codePath: src/01_mlp_hopper.py
                codePathLocal: src/01_mlp_hopper.py
                cpu_count: 10
                cpu_count_logical: 10
                disk:
                    /:
                        total: "494384795648"
                        used: "107189649408"
                email: shourya23.kaveti@gmail.com
                executable: /Library/Frameworks/Python.framework/Versions/3.13/bin/python3
                git:
                    commit: 99a6184b32a01adcfc16d36668ae081539ba12c5
                    remote: https://github.com/kaves29/kan-vs-mlp-rl-research.git
                host: Shouryas-MacBook-Pro.local
                memory:
                    total: "17179869184"
                os: macOS-26.5.1-arm64-arm-64bit-Mach-O
                program: /Users/shouryakaveti/VS_Projects/kan-vs-mlp-rl-research/src/01_mlp_hopper.py
                python: CPython 3.13.7
                root: /Users/shouryakaveti/VS_Projects/kan-vs-mlp-rl-research
                startedAt: "2026-06-10T12:06:02.446285Z"
                writerId: nvj1vbb34l1jjkqd4zhfhjxq62nacihe
        m: []
        python_version: 3.13.7
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
            "4": 3.13.7
            "5": 0.27.2
            "12": 0.27.2
            "13": darwin-arm64
